{% set name = "ruptures" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb6eda550d749d63d0ea1582f37d290fffa5fd6dc61513d971ef3429681d5255

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
      - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython
    - numpy

  run:
    - numpy
    - python
    - scipy

test:
  imports:
    - ruptures
    - ruptures.costs
    - ruptures.datasets
    - ruptures.detection
    - ruptures.metrics
    - ruptures.show
    - ruptures.utils

about:
  home: https://github.com/deepcharles/ruptures
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Change point detection for signals, in Python
  doc_url: http://ctruong.perso.math.cnrs.fr/ruptures-docs/build/html/index.html

extra:
  recipe-maintainers:
    - rpanai
    - deepcharles
    - oboulant
